---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hardwaremanagement.oran.openshift.io
  resources:
  - nodepools
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hardwaremanagement.oran.openshift.io
  resources:
  - nodepools/finalizers
  verbs:
  - update
- apiGroups:
  - hardwaremanagement.oran.openshift.io
  resources:
  - nodepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hardwaremanagement.oran.openshift.io
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hardwaremanagement.oran.openshift.io
  resources:
  - nodes/finalizers
  verbs:
  - update
- apiGroups:
  - hardwaremanagement.oran.openshift.io
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
